/**
 * GeneralTab Component
 *
 * General settings tab for the instance editor.
 */

import React, { useState } from 'react';
import type { AdminInstance } from '../../../types';
import { useAdminI18n } from '../../../hooks/useAdminI18n';

interface GeneralTabProps {
  instance: Partial<AdminInstance>;
  updateField: (path: string, value: unknown) => void;
  instanceId: string | null;
}

export const GeneralTab: React.FC<GeneralTabProps> = ({
  instance,
  updateField,
  instanceId,
}) => {
  const { t } = useAdminI18n();
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [copied, setCopied] = useState<string | null>(null);

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(id);
      setTimeout(() => setCopied(null), 2000);
    });
  };

  const shortcode = instanceId ? `[n8n_chat id="${instanceId}"]` : '[n8n_chat]';
  const phpFunction = instanceId
    ? `<?php n8n_chat_render('${instanceId}'); ?>`
    : '<?php n8n_chat_render(); ?>';

  return (
    <div className="n8n-chat-tab-content">
      <div className="n8n-chat-section">
        <h2 className="n8n-chat-section-title">{t('generalSettings', 'General Settings')}</h2>

        {/* Name */}
        <div className="n8n-chat-field">
          <label htmlFor="fc-name">
            {t('name', 'Name')} <span className="required">*</span>
          </label>
          <input
            type="text"
            id="fc-name"
            value={instance.name || ''}
            onChange={(e) => updateField('name', e.target.value)}
            className="regular-text"
            placeholder="e.g., Support Bot"
          />
          <p className="description">
            {t('internalNameDesc', "Internal name for organization. This won't be visible to visitors.")}
          </p>
        </div>

        {/* Status */}
        <div className="n8n-chat-field">
          <label>{t('status', 'Status')}</label>
          <div className="n8n-chat-radio-group">
            <label className="n8n-chat-radio">
              <input
                type="radio"
                name="status"
                checked={instance.isEnabled === true}
                onChange={() => updateField('isEnabled', true)}
              />
              <span className="n8n-chat-radio-label">
                <span className="n8n-chat-status-dot n8n-chat-status-active"></span>
                {t('active', 'Active')}
              </span>
            </label>
            <label className="n8n-chat-radio">
              <input
                type="radio"
                name="status"
                checked={instance.isEnabled === false}
                onChange={() => updateField('isEnabled', false)}
              />
              <span className="n8n-chat-radio-label">
                <span className="n8n-chat-status-dot n8n-chat-status-inactive"></span>
                {t('inactive', 'Inactive')}
              </span>
            </label>
          </div>
          <p className="description">
            {t('statusDesc', 'When inactive, the chat will not appear on your site.')}
          </p>
        </div>

        {/* Default Instance */}
        <div className="n8n-chat-field">
          <label className="n8n-chat-checkbox">
            <input
              type="checkbox"
              checked={instance.isDefault || false}
              onChange={(e) => updateField('isDefault', e.target.checked)}
            />
            <span>{t('setAsDefault', 'Set as default instance')}</span>
          </label>
          <p className="description">
            {t('defaultInstanceDesc', 'The default instance is used when no specific ID is provided in the shortcode.')}
          </p>
        </div>
      </div>

      {/* Advanced Options */}
      <div className="n8n-chat-section">
        <button
          type="button"
          className="n8n-chat-toggle-advanced"
          onClick={() => setShowAdvanced(!showAdvanced)}
          aria-expanded={showAdvanced}
        >
          <span className={`dashicons ${showAdvanced ? 'dashicons-arrow-down-alt2' : 'dashicons-arrow-right-alt2'}`}></span>
          {showAdvanced ? t('hide', 'Hide') : t('show', 'Show')} {t('advancedOptions', 'Advanced Options')}
        </button>

        {showAdvanced && (
          <div className="n8n-chat-advanced-content">
            {/* Slug */}
            <div className="n8n-chat-field">
              <label htmlFor="fc-slug">{t('slug', 'Slug')}</label>
              <input
                type="text"
                id="fc-slug"
                value={instanceId || t('autoGeneratedOnSave', 'Auto-generated on save')}
                readOnly
                className="regular-text code"
                disabled
              />
              <p className="description">
                {t('slugDesc', 'URL-friendly identifier (auto-generated from name).')}
              </p>
            </div>

            {/* Shortcode */}
            <div className="n8n-chat-field">
              <label>{t('shortcode', 'Shortcode')}</label>
              <div className="n8n-chat-copy-field">
                <code className="n8n-chat-code-display">{shortcode}</code>
                <button
                  type="button"
                  className="button button-small"
                  onClick={() => copyToClipboard(shortcode, 'shortcode')}
                >
                  {copied === 'shortcode' ? t('copied', '✓ Copied!') : t('copy', 'Copy')}
                </button>
              </div>
              <p className="description">
                {t('shortcodeDesc', 'Add this to any page or post to display the chat.')}
              </p>
            </div>

            {/* PHP Function */}
            <div className="n8n-chat-field">
              <label>{t('phpFunction', 'PHP Function')}</label>
              <div className="n8n-chat-copy-field">
                <code className="n8n-chat-code-display">{phpFunction}</code>
                <button
                  type="button"
                  className="button button-small"
                  onClick={() => copyToClipboard(phpFunction, 'php')}
                >
                  {copied === 'php' ? t('copied', '✓ Copied!') : t('copy', 'Copy')}
                </button>
              </div>
              <p className="description">
                {t('phpFunctionDesc', 'Use in theme templates to render the chat programmatically.')}
              </p>
            </div>

            {/* System Prompt */}
            <div className="n8n-chat-field">
              <label htmlFor="fc-system-prompt">{t('systemPrompt', 'System Prompt (Meta-Prompt)')}</label>
              <textarea
                id="fc-system-prompt"
                value={instance.systemPrompt || ''}
                onChange={(e) => updateField('systemPrompt', e.target.value)}
                rows={4}
                className="large-text"
                placeholder={t('systemPromptPlaceholder', 'Additional context sent with every message to n8n...')}
              />
              <p className="description">
                {t('systemPromptDesc', 'This text is sent to n8n with each request. Use dynamic tags like')} <code>{'{site_name}'}</code>, <code>{'{user_name}'}</code>, <code>{'{current_page_title}'}</code>.
              </p>
            </div>

            {/* Available Dynamic Tags */}
            <div className="n8n-chat-field">
              <label>{t('availableDynamicTags', 'Available Dynamic Tags')}</label>
              <div className="n8n-chat-tags-list">
                <span className="n8n-chat-tag" onClick={() => copyToClipboard('{site_name}', 'tag1')}>
                  {'{site_name}'}
                </span>
                <span className="n8n-chat-tag" onClick={() => copyToClipboard('{site_url}', 'tag2')}>
                  {'{site_url}'}
                </span>
                <span className="n8n-chat-tag" onClick={() => copyToClipboard('{user_name}', 'tag3')}>
                  {'{user_name}'}
                </span>
                <span className="n8n-chat-tag" onClick={() => copyToClipboard('{user_email}', 'tag4')}>
                  {'{user_email}'}
                </span>
                <span className="n8n-chat-tag" onClick={() => copyToClipboard('{user_role}', 'tag5')}>
                  {'{user_role}'}
                </span>
                <span className="n8n-chat-tag" onClick={() => copyToClipboard('{current_page_title}', 'tag6')}>
                  {'{current_page_title}'}
                </span>
                <span className="n8n-chat-tag" onClick={() => copyToClipboard('{current_page_url}', 'tag7')}>
                  {'{current_page_url}'}
                </span>
                <span className="n8n-chat-tag" onClick={() => copyToClipboard('{current_date}', 'tag8')}>
                  {'{current_date}'}
                </span>
                <span className="n8n-chat-tag" onClick={() => copyToClipboard('{current_time}', 'tag9')}>
                  {'{current_time}'}
                </span>
              </div>
              <p className="description">
                {t('dynamicTagsDesc', 'Click a tag to copy it. Tags are replaced with actual values when sent to n8n.')}
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default GeneralTab;
